from python:3.11-slim

WORKDIR /app

COPY tiny-py-local-stac/requirements.txt /app/requirements.txt

RUN apt update
RUN apt-get -y install g++
RUN apt -y install libgdal-dev
RUN pip install -r requirements.txt

COPY ./tiny-py-local-stac/pystac-create-collection.py /app/pystac-create-collection.py

CMD ["python", "/app/pystac-create-collection.py"]