services:
  http-server-images:
    build:
      context: .
      dockerfile: Dockerfile-http-images
    ports:
      - 8088:8088
    volumes:
      - ./tiny-py-local-stac/stac/images:/app/stac/images
  create-stac-collection:
    build:
      context: .
      dockerfile: Dockerfile-create-collection
    environment:
      - IMAGE_SERVER_HOST=http-server-images
    volumes:
      - ./tiny-py-local-stac/stac/images:/app/stac/images
      - ./tiny-py-local-stac/stac/stac-collection:/app/stac/stac-collection
    restart: on-failure
    depends_on:
      - http-server-images
  http-server-stac:
    build:
      context: .
      dockerfile: Dockerfile-http-stac
    ports:
      - 8089:8089
    volumes:
      - ./tiny-py-local-stac/stac/stac-collection:/app/stac/stac-collection
    depends_on:
      - create-stac-collection
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    environment:
      - STAC_SERVER_HOST=http-server-stac
    ports:
      - 8082:8082
  deepforest:
    build:
      context: .
      dockerfile: Dockerfile-deepforest
    ports:
      - 8081:8081
  quarkus-app:
    build:
      context: ./quarkus-docker
      dockerfile: Dockerfile.legacy-jar
    ports:
      - 8080:8080
    environment:
      - FREE_SAMPLES_HOST=flask
      - DEEPFOREST_URL=deepforest
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile-angular
    ports:
      - 3000:80
