FROM openjdk:17-jdk-slim AS build

ENV LANGUAGE='en_US:en'

USER root
RUN mkdir remote-sensing-api-backend
RUN mkdir build-output
RUN dir -s
COPY remote-sensing-api-backend /remote-sensing-api-backend

WORKDIR /remote-sensing-api-backend

RUN apt-get update && \
    apt-get install dos2unix && \
    apt-get clean
RUN dos2unix gradlew
RUN chmod +x gradlew
RUN ./gradlew build -Dquarkus.package.type=legacy-jar -Dquarkus.package.output-directory=/build-output

FROM openjdk:17-jdk-slim AS runtime


COPY --from=build /build-output/lib/* /deployments/lib/
COPY --from=build /build-output/*-runner.jar /deployments/quarkus-run.jar
COPY models/*.onnx /deployments/models/
COPY models/*.json /deployments/models/
COPY models/*.txt /deployments/models/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /deployments/quarkus-run.jar"]