from python:3.11-slim

WORKDIR /app

RUN apt update
RUN apt-get update
RUN apt-get -y install g++
RUN apt -y install libgdal-dev
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install flask
RUN pip install opencv-python-headless
RUN pip install deepforest

COPY ./tiny-deepforest-inference/deepforest-inference.py /app/deepforest-inference.py

COPY models/available-models.json ./models/DeepForestCustomTrained* /app

CMD ["python", "/app/deepforest-inference.py"]